sudo: required
services:
    - docker

before_install:
    - docker build -t krayush/test-app -f Dockerfile.Dev .

scripts:
    - docker run krayush/test-app npm run test:coverage

deploy:
    provider: s3
    access_key_id: ${access_key_id}
    secret_access_key: ${secret_access_key}
    bucket: ${s3_bucket}