sudo: required
services:
    - docker

before_install:
    - docker build -t krayush/test-app -f Dockerfile.Dev .

scripts:
    - docker run krayush/test-app npm run test:coverage

deploy:
    provider: elasticbeanstalk
    access_key_id: 
        secure: "Encrypted <access-key-id>=${access_key_id}"
    secret_access_key:
        secure: "Encypted <secret-access-key>="
    region: "ap-south-1"
    app: "aws-integration"
    env: "AwsIntegration-env"
    bucket_name: "elasticbeanstalk-ap-south-1-105609268698"