sudo: required
services:
    - docker

before_install:
    - docker build -t krayush/test-app -f Dockerfile.Dev .

scripts:
    - docker run krayush/test-app npm run test:coverage

deploy:
    provider: elasticbeanstalk
    access_key_id: 
        secure: "${access_key_id}"
    secret_access_key:
        secure: "${secret_access_key}"
    region: "ap-south-1"
    app: "aws-integration"
    env: "AwsIntegration-env"
    bucket_name: ${s3_bucket}